### ISSUE TITLE
Clean urls

### ISSUE THREAD

**Issue by gvoxcms** [cmsimple-xh/cmsimple-xh#240] opened 2017-05-14 17:05 UTC
There are still these awsome .&..&  urls which most other systems do not have - the web is stylish and 
cool - these urls are not

**Comment by cmb69** [comment] 2017-05-14 17:15
Yes, I fully agree, but there is no easy solution regarding plugins. Anyhow, this is a duplicate of #41.

**Closed by cmb69** 2017-05-14 17:15 UTC

**Comment by gvoxcms** [comment] 2017-05-14 18:05
Also a chache plugin would be useful which is common in higher class cmssses . 

There are plugins in github which allow to cache single html-files and others.

The site is then more fluently without long pauses
